---
- include_tasks: apt.yml
  when:
    - ansible_os_family == "Debian"
    - packages.apt is defined

- include_tasks: aur.yml
  when:
    - ansible_os_family == 'Archlinux'
    - packages.aur is defined

- include_tasks: pacman.yml
  when:
    - ansible_os_family == 'Archlinux'
    - packages.aur is defined

- include_tasks: pip.yml
