---
- include_role: name=software

- include_role: name=i3_config_addition

- name: Create config directory
  file:
    state: directory
    path: "{{ config_path }}"

- name: Set config
  copy:
    src: "{{ item }}"
    dest: "{{ config_path }}/{{ item }}"
  with_items:
    - "{{ config }}"
    - "{{ theme }}"
