---
- name: Create user to installfrom AUR
  block:
    - name: Create non-root user
      user:
        name: "{{ aur_user }}"

    - name: Set sudoers
      lineinfile:
        path: "/etc/sudoers.d/10-{{ aur_user }}"
        line: "{{ aur_user }} ALL=(ALL) NOPASSWD: /usr/bin/pacman"
        create: yes
        validate: 'visudo -cf %s'
  become: yes
